<?php /* Starfish Framework Template protection */ die(); ?>
<!-- History Section -->
<section id="history">
        <div class="container">
                <div class="row">
                        <div class="col-lg-12 text-center">
                                <h2 class="section-heading">History</h2>
                                <h3 class="section-subheading text-muted">Over the years, <strong>Starfish PHP Framework</strong> had many forms and new beginnings.</h3>
                        </div>
                </div>
                <div class="row">
                        <div class="col-lg-12">
                                <ul class="timeline">
                                        <li>
                                                <div class="timeline-image">
                                                        <img class="img-circle img-responsive" src="public/images/history.jpg" alt="">
                                                </div>
                                                <div class="timeline-panel">
                                                        <div class="timeline-heading">
                                                                <h4>2007-2008</h4>
                                                                <h4 class="subheading">The Beginnings</h4>
                                                        </div>
                                                        <div class="timeline-body">
                                                                <p class="text-muted">Back then, there weren't many frameworks or APIs to pick from. But the need for reusable code was present and strange shapes of code were generated by it.</p>
                                                        </div>
                                                </div>
                                        </li>

                                        <li class="timeline-inverted">
                                                <div class="timeline-image">
                                                        <img class="img-circle img-responsive" src="public/images/history.jpg" alt="">
                                                </div>
                                                <div class="timeline-panel">
                                                        <div class="timeline-heading">
                                                                <h4>2010</h4>
                                                                <h4 class="subheading">The first attempt</h4>
                                                        </div>
                                                        <div class="timeline-body">
                                                                <p class="text-muted">In 2010, a friends website required a lot of attention and what seemed to be a dedicated API. Therefore, an attempt to build a simple framework for APIs and small websites was made.</p>
                                                        </div>
                                                </div>
                                        </li>

                                        <li>
                                                <div class="timeline-spacer">
                                                        <i class="fa fa-quote-left fa-3x timeline-quote"></i>
                                                        <p class="text-muted">Ever since the first attempt, each website or web application the framework was used in got a new version of it, most with a little coppied code and everything else re-invented.</p>
                                                        <p class="text-muted">It was quite time consuming and frustrating!</p>
                                                </div>
                                        </li>

                                        <li class="timeline">
                                                <div class="timeline-image">
                                                        <img class="img-circle img-responsive" src="public/images/history.jpg" alt="">
                                                </div>
                                                <div class="timeline-panel">
                                                        <div class="timeline-heading">
                                                                <h4>January 2013</h4>
                                                                <h4 class="subheading">REST support was added</h4>
                                                        </div>
                                                        <div class="timeline-body">
                                                                <p class="text-muted">With a deeper understanding of the PHP capabilities and also its purpose, the framework was reoriented towards serving content for web applications.</p>
                                                        </div>
                                                </div>
                                        </li>

                                        <li class="timeline-inverted">
                                                <div class="timeline-image">
                                                        <img class="img-circle img-responsive" src="public/images/history.jpg" alt="">
                                                </div>
                                                <div class="timeline-panel">
                                                        <div class="timeline-heading">
                                                                <h4>03 March 2013</h4>
                                                                <h4 class="subheading">First version of the Framework</h4>
                                                        </div>
                                                        <div class="timeline-body">
                                                                <p class="text-muted">
                                                                        This was the first fully functional release of the framework.
                                                                        It implemented:
                                                                <ul>
                                                                        <li>Object Oriented Programming;</li>
                                                                        <li>Model-View-Controller;</li>
                                                                        <li>Front Controller;</li>
                                                                        <li>the Registry Pattern;</li>
                                                                        <li>the Singleton Pattern.</li>
                                                                </ul>
                                                                </p>
                                                </div>
                                        </div>
                                </li>

                        <li>
                                <div class="timeline-image">
                                        <img class="img-circle img-responsive" src="public/images/history.jpg" alt="">
                                </div>
                                <div class="timeline-panel">
                                        <div class="timeline-heading">
                                                <h4>24 March 2014</h4>
                                                <h4 class="subheading">Posted on Github</h4>
                                        </div>
                                        <div class="timeline-body">
                                                <p class="text-muted">In an effort to obtain better code, better results, the framework was published on Github. This is also the first time it was named <strong>Starfish PHP Framework</strong>.</p>
                                        </div>
                                </div>
                        </li>
                        <li class="timeline-inverted">
                                <div class="timeline-image">
                                        <img class="img-circle img-responsive" src="public/images/history.jpg" alt="">
                                </div>
                                <div class="timeline-panel">
                                        <div class="timeline-heading">
                                                <h4>15 October 2014</h4>
                                                <h4 class="subheading">The first version was launched</h4>
                                        </div>
                                        <div class="timeline-body">
                                                <p class="text-muted">We are looking forward to support and comments from those willing to help build a powerful and useful PHP tool.</p>
                                        </div>
                                </div>
                        </li>

                        <li class="timeline-inverted">
                                <div class="timeline-image">
                                        <h4><a href="https://github.com/cristidraghici/starfish/" class="white" target="_blank">Be Part <br> Of Our <br>Story!</a></h4>
                                </div>
                        </li>
                        </ul>
        </div>
        </div>
</div>
</section>